version: 1
disable_existing_loggers: false

# 日志保留策略配置
log_retention:
  days_to_keep: 30  # 保留的日志天数
  check_interval_hours: 24  # 检查间隔小时数

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(pathname)s:%(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  file:
    class: logging.FileHandler
    level: INFO
    formatter: detailed
    filename: logs/date.log  # 这将在代码中被动态替换为当前日期
    encoding: utf-8
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

loggers:
  '':  # 根日志器
    handlers: [file, console]
    level: INFO
    propagate: true